version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Create keystore.properties
          command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > keystore.properties
      - run:
          name: Decode Android key storeS
          command: echo $KEYSTORE | base64 -d | tee keystore app/keystore > /dev/null
      - run:
          name: Create Google Play Key
          command: echo $GPLAY_SERVICE_ACCOUNT_KEY_JSON | base64 -d | tee google-play-key.json /home/circleci/project/google-play-key.json > /dev/null
      - run:
          name : Check google-play-key
          command: cat /home/circleci/project/google-play-key.json
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run TestsN
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts: 
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - run:
          name: Install fastlane first
          command: bundle install
      - run:
          name: Install fastlane bundler
          command: gem install bundler
      - run:
          name: Run supply init
          command: bundle exec fastlane supply init
      - run:
          name: Generate bundle aab
          command: bundle exec fastlane bundling
      - run:
          name: Upload aab release
          command: bundle exec fastlane supply --aab /project/app/build/outputs/bundle/proRelease/app-pro-release.aab
      - run:
          name: Execute fastlane
          command: bundle exec fastlane deploy